name: Issue Categorizer

on:
  workflow_dispatch
#  issues:
 #   types: [opened]

jobs:
  categorize-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue body
        id: get_issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const body = context.payload.issue.body ? context.payload.issue.body.toLowerCase() : '';
            core.setOutput('issue_number', issue_number);
            core.setOutput('body', body);

      - name: Categorize and comment
        uses: actions/github-script@v7
        with:
          script: |
            const body = process.env.body;
            let category = 'Other';
            if (["component", "ui", "button", "form", "dialog", "modal", "input", "table"].some(word => body.includes(word))) {
              category = 'UI';
            } else if (["api", "endpoint", "rest", "http", "request", "response"].some(word => body.includes(word))) {
              category = 'API';
            } else if (["model", "ai", "ml", "machine learning", "data science"].some(word => body.includes(word))) {
              category = 'Spike';
            }
            const issue_number = process.env.issue_number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(issue_number),
              body: `Category: **${category}**`
            });
        env:
          body: ${{ steps.get_issue.outputs.body }}
          issue_number: ${{ steps.get_issue.outputs.issue_number }}
